### ISSUE TITLE
Please add layout to map /usr/lib/libnetplan* 

### ISSUE THREAD

**Issue by mvo5** [anonymouse64/test-snapd-netplan-apply#1]
The snap in edge is currently failing with:
```
Traceback (most recent call last):
  File "/snap/test-snapd-netplan-apply/358/usr/sbin/netplan", line 20, in <module>
    from netplan import Netplan
  File "/snap/test-snapd-netplan-apply/358/usr/share/netplan/netplan/__init__.py", line 18, in <module>
    from netplan.cli.core import Netplan
  File "/snap/test-snapd-netplan-apply/358/usr/share/netplan/netplan/cli/core.py", line 24, in <module>
    import netplan.cli.utils as utils
  File "/snap/test-snapd-netplan-apply/358/usr/share/netplan/netplan/cli/utils.py", line 41, in <module>
    lib.netplan_parse_yaml.argtypes = [ctypes.c_char_p, ctypes.POINTER(ctypes.POINTER(_GError))]
  File "/snap/test-snapd-netplan-apply/358/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/snap/test-snapd-netplan-apply/358/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /snap/test-snapd-netplan-apply/358/usr/bin/python3: undefined symbol: netplan_parse_yaml
```
on systems with python3.5 (maybe more).

The reason is that the code in netplan uses:
```
lib = ctypes.CDLL(ctypes.util.find_library('netplan'))
```
but older versions of python do not honor LD_LIBRARY_PATH so the python code does find libnetplan in the /snap/test-snapd-netplan-apply dir. 

It seems using a layout might be the easiest option to fix this but ideas welcome.

**Comment by anonymouse64** [comment]
Unfortunately this doesn't "just work" to set the layout, but also tbh we never finished the work to make just calling the version of netplan bundled in the base snap work from i.e. a shell script, so if we finished that we could get rid of this snap entirely and just have a simple shell script instead. I explored there in snapcore/snapd#9784
